// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace YakimGamesTaskBundle.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20240408154404_ChangedToOneToManyTaskRealtion")]
    partial class ChangedToOneToManyTaskRealtion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("YakimGamesTaskBundle.Data.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BundleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletionCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("YakimGamesTaskBundle.Data.TaskBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskBundles");
                });

            modelBuilder.Entity("YakimGamesTaskBundle.Data.ProjectTask", b =>
                {
                    b.HasOne("YakimGamesTaskBundle.Data.TaskBundle", "Bundle")
                        .WithMany("Tasks")
                        .HasForeignKey("BundleId");

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("YakimGamesTaskBundle.Data.TaskBundle", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
